applied PackageJanitor

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -44,3 +44,14 @@ jobs:
           TERM=dumb make -C CatReps -j $(nproc) --output-sync ci-test
           cp ./CatReps/.codecov.yml ./
           curl -s https://codecov.io/bash | bash
+          git config --global user.name "Bot"
+          git config --global user.email "empty"
+          cd CatReps
+          CUR_SHA=$(git rev-parse --verify HEAD)
+          if [ "${{ matrix.image }}" = "gapsystem/gap-docker" ] && [ "$CUR_SHA" = "$(git rev-parse origin/master)" ] && [ $(dirname "$GITHUB_REPOSITORY") = "homalg-project" ]; then \
+            git worktree add gh-pages/ gh-pages || (echo "There was an error. Make sure there is a branch named 'gh-pages'. See https://github.com/homalg-project/PackageJanitor#error-there-was-an-error-make-sure-there-is-a-branch-named-gh-pages"; exit 1); \
+            git checkout master; \
+            ./make_dist.sh --token "${{ secrets.GITHUB_TOKEN }}"; \
+          else \
+            echo "Not making a release."; \
+          fi
